name: networkviewer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  tree_view: ^0.0.5

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
